name: factorio-headless
summary: Server for Factorio a game in which you build and maintain factories
description: |
  Change server settings and install mods in terminal with command line completion. Automate server installations.

    factorio-headless

adopt-info: factorio
base: core18
grade: stable
confinement: strict
architectures:
  - build-on: amd64

system-usernames:
  snap_daemon: shared

apps:
  factorio-headless:
    command: wrapper factorio-headless
    completer: completion
    plugs: &plugs
      - home
      - network
      - network-bind
  
  admins:
    command: wrapper admins
    completer: completion
    plugs: *plugs

  mods:
    command: wrapper mods
    completer: completion
    plugs: *plugs

  service:
    command: wrapper service
    daemon: simple
    stop-timeout: 1m
    plugs: *plugs

parts:
  factorio:
    source: https://www.factorio.com/get-download/latest/headless/linux64
    source-type: tar
    plugin: dump
    override-build: |
      snapcraftctl build
      snapcraftctl set-version `cat data/base/info.json | jq -r .version`
    build-packages:
      - jq
    organize:
      '*': factorio/

  config:
    source: config/
    plugin: dump
    organize:
      '*': factorio/

  scripts:
    source: scripts/
    plugin: dump
    stage-packages:
      - setpriv
      - curl
      - jq
