name: Publish Factorio Headless Snap

on:
  schedule:
  - cron: "30 22 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: release
      run: |
        sudo apt-get install -y jq

        releases=$(wget -qO- "https://factorio.com/api/latest-releases")
        if [ -z "$releases" ]; then
          echo "Error getting factorio releases"
          exit 1
        fi

        series="X-Ubuntu-Series: 16"
        details="https://api.snapcraft.io/api/v1/snaps/details/factorio-headless"

        stable=$(wget -qO- --header "$series" "$details?channel=stable" | jq -r .version)
        if [ -z "$stable" ]; then
          echo "Error getting snap stable version"
          exit 1
        fi

        stable_release=$(echo "$releases" | jq -r .stable.headless)
        if [ ! "$stable" = "$stable_release" ]; then
          export STABLE_RELEASE=$stable_release
        fi

        beta=$(wget -qO- --header "$series" "$details?channel=beta" | jq -r .version)
        if [ -z "$stable" ]; then
          echo "Error getting snap beta version"
          exit 1
        fi

        beta_release=$(echo "$releases" | jq -r .experimental.headless)
        if [ ! "$beta" = "$beta_release" ]; then
          export BETA_RELEASE=$beta_release
        fi

    - id: checkout
      if: env.BETA_RELEASE != "" || env.STABLE_RELEASE != ""
      uses: actions/checkout@v2

    - id: build
      if: env.BETA_RELEASE != "" || env.STABLE_RELEASE != ""
      uses: snapcore/action-build@v1

    - id: publish-beta
      if: env.BETA_RELEASE != ""
      uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: beta

    - id: publish-stable
      if: env.STABLE_RELEASE != ""
      uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: stable

